[book]
authors = ["jeffzh4ng"]
language = "en"
multilingual = false
src = "src"
title = "Singularity Systems: Zero to Hero"

[preprocessor.katex]
after = ["links"]

[preprocessor.repl]
python.enable = true
python.loading = "lazy"